#
# i386.make
#
# Created by Jean-Pierre Höhmann on 18-08-25.
#
# Copyright 2018 Jean-Pierre Höhmann (@NuvandaPV) <jean-pierre@höhmann.info>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Architecture dependent make configuration for building the kernel for i386.
#

ARCH_CFLAGS_DEFAULT=
ARCH_CFLAGS_EXTRA=
ARCH_CPPFLAGS_DEFAULT=
ARCH_CPPFLAGS_EXTRA=
ARCH_LDFLAGS_DEFAULT=
ARCH_LDFLAGS_EXTRA=
ARCH_LIBS_DEFAULT=
ARCH_LIBS_EXTRA=

KERNEL_ARCH_CFLAGS_DEFAULT=
KERNEL_ARCH_CFLAGS_EXTRA=
KERNEL_ARCH_CPPFLAGS_DEFAULT=
KERNEL_ARCH_CPPFLAGS_EXTRA=
KERNEL_ARCH_LDFLAGS_DEFAULT=
KERNEL_ARCH_LDFLAGS_EXTRA=
KERNEL_ARCH_LIBS_DEFAULT=
KERNEL_ARCH_LIBS_EXTRA=

ARCH_CFLAGS_DEFAULT:=$(ARCH_CFLAGS_DEFAULT)
ARCH_CPPFLAGS_DEFAULT:=$(ARCH_CPPFLAGS_DEFAULT)
ARCH_LDFLAGS_DEFAULT:=$(ARCH_LDFLAGS_DEFAULT)
ARCH_LIBS_DEFAULT:=$(ARCH_LIBS_DEFAULT)

ARCH_CFLAGS_EXTRA:=$(ARCH_CFLAGS_EXTRA)
ARCH_CPPFLAGS_EXTRA:=$(ARCH_CPPFLAGS_EXTRA)
ARCH_LDFLAGS_EXTRA:=$(ARCH_LDFLAGS_EXTRA)
ARCH_LIBS_EXTRA:=$(ARCH_LIBS_EXTRA)

ARCH_CFLAGS?=$(ARCH_CFLAGS_DEFAULT)
ARCH_CPPFLAGS?=$(ARCH_CPPFLAGS_DEFAULT)
ARCH_LDFLAGS?=$(ARCH_LDFLAGS_DEFAULT)
ARCH_LIBS?=$(ARCH_LIBS_DEFAULT)

ARCH_CFLAGS:=$(ARCH_CFLAGS)
ARCH_CPPFLAGS:=$(ARCH_CPPFLAGS)
ARCH_LDFLAGS:=$(ARCH_LDFLAGS)
ARCH_LIBS:=$(ARCH_LIBS)

KERNEL_ARCH_CFLAGS_DEFAULT:=$(ARCH_CFLAGS) $(KERNEL_ARCH_CFLAGS_DEFAULT)
KERNEL_ARCH_CPPFLAGS_DEFAULT:=$(ARCH_CPPFLAGS) $(KERNEL_ARCH_CPPFLAGS_DEFAULT)
KERNEL_ARCH_LDFLAGS_DEFAULT:=$(ARCH_LDFLAGS) $(KERNEL_ARCH_LDFLAGS_DEFAULT)
KERNEL_ARCH_LIBS_DEFAULT:=$(ARCH_LIBS) $(KERNEL_ARCH_LIBS_DEFAULT)

KERNEL_ARCH_CFLAGS_EXTRA:=$(ARCH_CFLAGS_EXTRA) $(KERNEL_ARCH_CFLAGS_EXTRA)
KERNEL_ARCH_CPPFLAGS_EXTRA:=$(ARCH_CPPFLAGS_EXTRA) $(KERNEL_ARCH_CPPFLAGS_EXTRA)
KERNEL_ARCH_LDFLAGS_EXTRA:=$(ARCH_LDFLAGS_EXTRA) $(KERNEL_ARCH_LDFLAGS_EXTRA)
KERNEL_ARCH_LIBS_EXTRA:=$(ARCH_LIBS_EXTRA) $(KERNEL_ARCH_LIBS_EXTRA)

KERNEL_ARCH_CFLAGS?=$(KERNEL_ARCH_CFLAGS_DEFAULT)
KERNEL_ARCH_CPPFLAGS?=$(KERNEL_ARCH_CPPFLAGS_DEFAULT)
KERNEL_ARCH_LDFLAGS?=$(KERNEL_ARCH_LDFLAGS_DEFAULT)
KERNEL_ARCH_LIBS?=$(KERNEL_ARCH_LIBS_DEFAULT)

KERNEL_ARCH_CFLAGS:=$(KERNEL_ARCH_CFLAGS)
KERNEL_ARCH_CPPFLAGS:=$(KERNEL_ARCH_CPPFLAGS)
KERNEL_ARCH_LDFLAGS:=$(KERNEL_ARCH_LDFLAGS)
KERNEL_ARCH_LIBS:=$(KERNEL_ARCH_LIBS)

ARCH_CFLAGS:=$(ARCH_CFLAGS) $(ARCH_CFLAGS_EXTRA)
ARCH_CPPFLAGS:=$(ARCH_CPPFLAGS) $(ARCH_CPPFLAGS_EXTRA)
ARCH_LDFLAGS:=$(ARCH_LDFLAGS) $(ARCH_LDFLAGS_EXTRA)
ARCH_LIBS:=$(ARCH_LIBS) $(ARCH_LIBS_EXTRA)

KERNEL_ARCH_CFLAGS:=$(KERNEL_ARCH_CFLAGS) $(KERNEL_ARCH_CFLAGS_EXTRA)
KERNEL_ARCH_CPPFLAGS:=$(KERNEL_ARCH_CPPFLAGS) $(KERNEL_ARCH_CPPFLAGS_EXTRA)
KERNEL_ARCH_LDFLAGS:=$(KERNEL_ARCH_LDFLAGS) $(KERNEL_ARCH_LDFLAGS_EXTRA)
KERNEL_ARCH_LIBS:=$(KERNEL_ARCH_LIBS) $(KERNEL_ARCH_LIBS_EXTRA)

KERNEL_ARCH_OBJS=\
$(ARCHDIR)/boot.o \
$(ARCHDIR)/tty.o \
$(ARCHDIR)/gdt.o \
$(ARCHDIR)/cpu.o \
$(ARCHDIR)/pg.o \
$(ARCHDIR)/mmu.o \
$(ARCHDIR)/pfa.o \
